# Sample workflow to access AWS resources when workflow is tied to branch
# The workflow Creates static website using aws s3
name: AWS example workflow
on:
  push:
    branches:
      - main
      - staging
      - development
env:
#   BUCKET_NAME : "terraform02-bucket01"
  AWS_REGION : "ap-northeast-1"
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  S3PackageUpload:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: Set environment variables for each branch
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "BUCKET_NAME=terraform02-bucket01-main" >> $GITHUB_ENV
            echo "env=main" >> $GITHUB_ENV
          elif [ "${{ github.ref }}" == "refs/heads/staging" ]; then
            echo "BUCKET_NAME=terraform02-bucket01-staging" >> $GITHUB_ENV
            echo "env=stg" >> $GITHUB_ENV
          elif [ "${{ github.ref }}" == "refs/heads/development" ]; then
            echo "BUCKET_NAME=terraform02-bucket01-development" >> $GITHUB_ENV
            echo "env=dev" >> $GITHUB_ENV
          fi
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.IAM_ROLE_ARN }}
          role-session-name: samplerolesession
          aws-region: ${{ env.AWS_REGION }}
      # Upload a file to AWS s3
      - name:  Copy index.html to s3
        run: |
          aws s3 cp ./index.html s3://${{ env.BUCKET_NAME }}/
      # Debug
      - name:  debug
        run: |
          aws s3 ls
          ls -lR
      # 01_ec2/ apply
      - name:  terraform init
        run: |
          terraform -chdir=01_ec2 init
      - name:  terraform validate
        run: |
          terraform -chdir=01_ec2 validate
      - name:  terraform apply
        run: |
          terraform -chdir=01_ec2 apply -auto-approve

